custom_handlers_task/custom_handlers_task/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

custom_handlers_task/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),

]

custom_handlers_task/home/models.py
from django.db import models

# Create your models here.

custom_handlers_task/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    # Переменная exception содержит отладочную информацию, 
    # выводить её в шаблон пользователской страницы 404 мы не станем
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

custom_handlers_task/home/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'home/index.html', {})

custom_handlers_task/templates/base.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8"> 

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>	 
    <main>
      <div class="container py-5">
        {% block content %}Контент не подвезли :({% endblock %}
      </div>
    </main>	 
  </body>
</html>

custom_handlers_task/templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Custom CSRF check error{% endblock %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

custom_handlers_task/templates/home/index.html
{% extends "base.html" %}
{% block title %}Главная{% endblock %}
{% block content %}
    <h1>Главная с кнопкой но без csrf_token</h1>
    <form method="post" action="{% url 'home:index' %}">
      <button type="submit" class="btn btn-primary">
      Push me and then just touch me!!!
    </button>

    </form>
{% endblock %}